# -*- coding: utf-8 -*-
"""research_methods_Sivagurunathan_Srija_Pavithraa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrjMFmlZhAQ1rsmu52lLcrrKtA0bl7Bw
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm

#LOAD DATA

df = pd.read_excel("Market return_updated.xlsx")

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')
df.set_index('Date', inplace=True)

print("Data Loaded Successfully")

#CONVERT RF TO DECIMAL

df['RF'] = df['RF'] / 100

#DEFINE ETFs

etfs = ['XLE','XLF','XLP','XLK','XLU']

#CREATE EXCESS RETURNS

for etf in etfs:
    df[etf + '_excess'] = df[etf] - df['RF']

df['SPX_excess'] = df['SPX'] - df['RF']

print("Excess returns created")

#MODEL A — SENTIMENT ONLY (NO MARKET FACTOR)

results_no_market = []

for etf in etfs:

    X = sm.add_constant(df[['SENT_ORTH']])
    y = df[etf + '_excess']

    model = sm.OLS(y, X).fit(cov_type='HC3')

    results_no_market.append({
        'ETF': etf,
        'Alpha': model.params['const'],
        'Behavioural_Beta': model.params['SENT_ORTH'],
        'Sentiment_pvalue': model.pvalues['SENT_ORTH'],
        'R_squared': model.rsquared
    })

betas_no_market = pd.DataFrame(results_no_market)

print("\n=== Behavioural Beta ONLY (No Market) ===")
print(betas_no_market)

#MODEL B — CAPM (MARKET BETA)

capm_results = []

for etf in etfs:

    X = sm.add_constant(df['SPX_excess'])
    y = df[etf + '_excess']

    model = sm.OLS(y, X).fit(cov_type='HC3')

    capm_results.append({
        'ETF': etf,
        'Market_Beta': model.params['SPX_excess'],
        'p_value': model.pvalues['SPX_excess'],
        'R_squared': model.rsquared
    })

capm_df = pd.DataFrame(capm_results)

print("\n=== CAPM Results ===")
print(capm_df)

#MODEL C — MARKET + SENTIMENT (BEHAVIOURAL BETA)

results_market = []

for etf in etfs:

    X = df[['SPX_excess','SENT_ORTH']]
    X = sm.add_constant(X)

    y = df[etf + '_excess']

    model = sm.OLS(y, X).fit(cov_type='HC3')

    results_market.append({
        'ETF': etf,
        'Alpha': model.params['const'],
        'Market_Beta': model.params['SPX_excess'],
        'Behavioural_Beta': model.params['SENT_ORTH'],
        'Sentiment_pvalue': model.pvalues['SENT_ORTH'],
        'R_squared': model.rsquared
    })

betas_market = pd.DataFrame(results_market)

print("\n=== Behavioural Beta (Market + Sentiment) ===")
print(betas_market)

#PREDICTIVE REGRESSION
#Test whether current investor sentiment predicts future ETF returns
df_future = df.copy()

for etf in etfs:
    df_future[etf + '_lead'] = df_future[etf + '_excess'].shift(-1)

df_future = df_future.dropna()

predict_results = []

for etf in etfs:

    X = sm.add_constant(df_future[['SENT_ORTH']])
    y = df_future[etf + '_lead']

    model = sm.OLS(y, X).fit(cov_type='HC3')

    predict_results.append({
        'ETF': etf,
        'Predict_Coeff': model.params['SENT_ORTH'],
        'p_value': model.pvalues['SENT_ORTH']
    })

predict_df = pd.DataFrame(predict_results)

print("\n=== Predictive Regression ===")
print(predict_df)

#HIGH - LOW SPREAD TEST
#behavioural betas to examine whether sentiment exposure produces abnormal return differences
sorted_betas = betas_market.sort_values('Behavioural_Beta')

low_etf = sorted_betas.iloc[0]['ETF']
high_etf = sorted_betas.iloc[-1]['ETF']

print("\nLow behavioural beta ETF:", low_etf)
print("High behavioural beta ETF:", high_etf)

df['Spread'] = df[high_etf + '_excess'] - df[low_etf + '_excess']

spread_model = sm.OLS(df['Spread'],
                      sm.add_constant(np.ones(len(df)))).fit(cov_type='HC3')

print("\n=== High-Low Spread Test ===")
print(spread_model.summary())

#INTERACTION REGIME TEST
#Examine whether the impact of sentiment changes during periods of
#high market volatility by interacting sentiment with a volatility regime dummy
df['High_Vol'] = (df['SPX_excess'].abs() > df['SPX_excess'].std()).astype(int)

print("\n=== Interaction Model Results ===")

for etf in etfs:

    df['Interaction'] = df['SENT_ORTH'] * df['High_Vol']

    X = sm.add_constant(df[['SPX_excess','SENT_ORTH','Interaction']])
    y = df[etf + '_excess']

    model = sm.OLS(y, X).fit(cov_type='HC3')

    print("\nETF:", etf)
    print(model.summary())

#FF5 + SENTIMENT ROBUSTNESS
#to verify that the sentiment effect is not captured by standard risk factors
ff_results = []

for etf in etfs:

    X = df[['SPX_excess','SMB','HML','RMW','CMA','SENT_ORTH']]
    X = sm.add_constant(X)

    y = df[etf + '_excess']

    model = sm.OLS(y, X).fit(cov_type='HC3')

    ff_results.append({
        'ETF': etf,
        'Sentiment_Coeff': model.params['SENT_ORTH'],
        'Sentiment_pvalue': model.pvalues['SENT_ORTH'],
        'R_squared': model.rsquared
    })

ff_df = pd.DataFrame(ff_results)

print("\n=== FF5 + SPX + Sentiment Robustness ===")
print(ff_df)

#POOLED REGRESSION (PANEL STYLE)
#to evaluate the overall impact of sentiment across sectors
stacked_df = pd.DataFrame()

for etf in etfs:

    temp = df[['SPX_excess','SENT_ORTH']].copy()
    temp['excess'] = df[etf + '_excess']
    temp['ETF'] = etf

    stacked_df = pd.concat([stacked_df, temp])

X = sm.add_constant(stacked_df[['SPX_excess','SENT_ORTH']])
y = stacked_df['excess']

pooled_model = sm.OLS(y, X).fit(cov_type='HC3')

print("\n=== Pooled Regression ===")
print(pooled_model.summary())

#DESCRIPTIVE STATISTICS

summary_vars = []

for etf in etfs:
    summary_vars.append(etf + '_excess')

summary_vars += ['SPX_excess','SENT_ORTH']

summary_table = df[summary_vars].agg(['mean','std','min','max']).T

summary_table.columns = ['Mean','Std_Dev','Min','Max']

print("\n=== Descriptive Statistics ===")
print(summary_table)


#CORRELATION MATRIX

corr_matrix = df[summary_vars].corr()

print("\n=== Correlation Matrix ===")
print(corr_matrix)

#ECONOMIC MAGNITUDE

print("\nStandard Deviation of Sentiment:")
print(df['SENT_ORTH'].std())